# Generated by Django 3.0.8 on 2021-04-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="places",
            old_name="lattitude",
            new_name="latitude",
        ),
    ]
